counter:
  cuboid:
  - - 1.9740854572695874
    - 1.7015776263695614
  - - 1.5785125219065683
    - 2.1127752522538734
  - - 1.5053324616863417
    - 2.0500610970123607
  - - 1.715601983862148
    - 1.8287139964938963
  last_updated: '2024-05-16 12:03:13.636677'
  location:
    position:
      x: 1.9469668422327167
      y: 1.5762247358933623
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.7558695574254443
      w: 0.6547222404634373
tables:
  table0:
    last_updated: '2024-05-16 12:03:13.636677'
    location:
      position:
        x: 2.3944055409380534
        y: -0.06762505794377859
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.776456002664628
        w: 0.6301714654965481
        semantic: end
    num_persons: 0
    objects_cuboid:
    - - -0.18203496932983398
      - -0.26015329360961914
    - - 2.8306732177734375
      - 0.13982903957366943
    - - 2.0205249786376953
      - 0.07376503944396973
    - - 1.967973232269287
      - 0.06428396701812744
    order: []
    persons_cuboid:
    - - 3.221827268600464
      - 0.8606802225112915
    - - 0.8337788581848145
      - 0.3184191584587097
    - - 1.0028605461120605
      - -1.0100688934326172
    - - 2.8332748413085938
      - -1.169182300567627
    pre_location:
      position:
        x: -0.029312069441308063
        y: -0.09354620465651603
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.04133649816557395
        w: 0.9991452816880073
    status: unvisited
  table1:
    last_updated: '2024-05-16 12:03:13.636677'
    location:
      position:
        x: -1.2551871070794756
        y: 1.5999794668066123
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.7753121477683648
        w: 0.6315782402227023
    objects_cuboid:
    - - -0.6005063056945801
      - 3.191981554031372
    - - -0.40178823471069336
      - 3.5316221714019775
    - - -1.5742111206054688
      - 3.5877606868743896
    - - -1.4973807334899902
      - 3.2101352214813232
    persons_cuboid:
    - - -0.0979769229888916
      - 2.668891191482544
    - - -0.1757817268371582
      - 3.074601411819458
    - - -1.4325685501098633
      - 3.088010549545288
    - - -1.268871784210205
      - 2.678766965866089
    pre_location:
      position:
        x: -0.20535010803511777
        y: 1.76132777626305
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.4714864074194242
        w: 0.8818733285561622
wait:
  approach1:
    position: 
      x: 3.8513665380637687
      y: 2.668642763709559
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.8240212934244492
      w: 0.5665588301166065
  approach2:
    position: 
      x: 3.535156570803559
      y: 2.825342685953446
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.967676573048101
      w: 0.252194468563217
  cuboid:
  - - 3.3376955492310016
    - 2.9759670421600717
  - - 3.885295396395047
    - 3.4219736624547337
  - - 3.9889343891584077
    - 2.6455473289184157
  - - 3.203195687824157
    - 2.5416210803738455
  last_updated: '2024-05-16 12:03:13.636677'
  location:
    position:
      x: 3.1242881017125086
      y: 2.519295334887309
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.6935006384930328
      w: 0.7204560114328673
objects: {"cup" : "coffee", "banana": "banana", "bottle": "cocacola"}
yolo_person_model: "yolo11n-seg.pt"
yolo_objects_model: "yolo11n-seg.pt"
yolo_counter_model: "yolo11n-seg.pt"