counter:
  cuboid:
    - - 1.9740854572695874
      - 1.7015776263695614
    - - 1.5785125219065683
      - 2.1127752522538734
    - - 1.5053324616863417
      - 2.0500610970123607
    - - 1.715601983862148
      - 1.8287139964938963
  last_updated: '2024-05-16 12:03:13.636677'
  location:
    position:
      x: 0.6032014627278357
      y: 2.503004529274854
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9008735169340348
      w: 0.4340816818144982
tables:
  table0:
    last_updated: '2024-05-16 12:03:13.636677'
    location:
      position:
        x: -0.43473387489676374
        y: 0.9476352711850697
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.3137141177416937
        w: 0.9495174839514808
    num_persons: 0
    objects_cuboid:
      - - -0.18203496932983398
        - -0.26015329360961914
      - - 2.8306732177734375
        - 0.13982903957366943
      - - 2.0205249786376953
        - 0.07376503944396973
      - - 1.967973232269287
        - 0.06428396701812744
    order: [ ]
    persons_cuboid:
      - - 3.221827268600464
        - 0.8606802225112915
      - - 0.8337788581848145
        - 0.3184191584587097
      - - 1.0028605461120605
        - -1.0100688934326172
      - - 2.8332748413085938
        - -1.169182300567627
    pre_location:
      position:
        x: -0.029312069441308063
        y: -0.09354620465651603
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.04133649816557395
        w: 0.9991452816880073
    status: unvisited
  table1:
    last_updated: '2024-05-16 12:03:13.636677'
    location:
      position:
        x: -0.2520586446419259
        y: 2.0697032769677217
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.7745196180814466
        w: 0.6325498883147243
    objects_cuboid:
      - - -0.6005063056945801
        - 3.191981554031372
      - - -0.40178823471069336
        - 3.5316221714019775
      - - -1.5742111206054688
        - 3.5877606868743896
      - - -1.4973807334899902
        - 3.2101352214813232
    persons_cuboid:
      - - -0.0979769229888916
        - 2.668891191482544
      - - -0.1757817268371582
        - 3.074601411819458
      - - -1.4325685501098633
        - 3.088010549545288
      - - -1.268871784210205
        - 2.678766965866089
    pre_location:
      position:
        x: -0.20535010803511777
        y: 1.76132777626305
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.4714864074194242
        w: 0.8818733285561622
wait:
  approach1:
    position:
      x: 1.590142582097317
      y: 3.5077809694675626
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.45144624303861935
      w: 0.8922983187512548
  approach2:
    position:
      x: 3.535156570803559
      y: 2.825342685953446
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.967676573048101
      w: 0.252194468563217
  cuboid:
    - [ 1.370010256767273, 2.3785524368286133 ]
    - [ 2.9463655948638916, 4.096718788146973 ]
    - [ 1.565426230430603, 5.085967063903809 ]
    - [ 1.1615663766860962, 3.667177438735962 ]


  last_updated: '2024-05-16 12:03:13.636677'
  location:
    position:
      x: 0.9033915917210108
      y: 1.9126536797667475
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.45115143742533476
      w: 0.8924474105005035
objects: { "cup": "coffee", "banana": "banana", "bottle": "cocacola" }
yolo_person_model: "yolo11n-seg.pt"
yolo_objects_model: "yolo11n-seg.pt"
yolo_counter_model: "yolo11n-seg.pt"