counter:
  cuboid:
    - - 6.385480886114623
      - 26.053033932057588
    - - 6.512335358611623
      - 25.466639879090895
    - - 7.098741359648088
      - 25.593552439607766
    - - 6.971886887151087
      - 26.17994649257446
  last_updated: '2024-06-09 17:13:12.316195'
  location:
    orientation:
      w: 0.9956514044661379
      x: 0.0
      y: 0.0
      z: 0.09315729056068087
    position:
      x: 6.021648694375644
      y: 25.69783072605752
      z: 0.0
tables:
  table0:
    last_updated: '2024-06-09 17:06:29.140552'
    location:
      orientation:
        w: 0.13258267564351778
        x: 0.0
        y: 0.0
        z: -0.9911719498246536
      position:
        x: 9.41866902109906
        y: 26.351774527034294
        z: 0.0
      semantic: end
    num_persons: 0
    objects_cuboid:
      - - 9.033581583294428
        - 25.805967137066013
      - - 8.852281808376198
        - 26.939316643384483
      - - 8.259815970776838
        - 26.844531575478726
      - - 8.441115745695068
        - 25.711182069160255
    order: [ ]
    persons_cuboid:
      - - 9.94965761597872
        - 25.143930179733303
      - - 9.516114675956866
        - 27.85411378179921
      - - 7.343739938092545
        - 27.506568532811436
      - - 7.7772828781144
        - 24.79638493074553
    pre_location:
      orientation:
        w: 0.6981442535161398
        x: 0.0
        y: 0.0
        z: -0.7159571225166993
      position:
        x: 3.4185893265341467
        y: 1.5007719904983003
        z: 0.0
    status: unvisited
  table1:
    last_updated: '2024-06-09 17:08:30.928953'
    location:
      orientation:
        w: 0.09526670117283224
        x: 0.0
        y: 0.0
        z: -0.9954517846925818
      position:
        x: 5.712413766768246
        y: 21.407430719219526
        z: 0.0
    objects_cuboid:
      - - 5.407575647338826
        - 20.96312899531904
      - - 5.196037608221362
        - 21.734394479759732
      - - 4.424543687273396
        - 21.52312444121242
      - - 4.636081726390859
        - 20.75185895677173
    persons_cuboid:
      - - 6.390607607404255
        - 20.403133549425657
      - - 5.755993490051864
        - 22.716930002747734
      - - 3.4415117272079665
        - 22.083119887105806
      - - 4.076125844560358
        - 19.76932343378373
    pre_location:
      orientation:
        w: 0.679755237535674
        x: 0.0
        y: 0.0
        z: -0.7334390343053875
      position:
        x: 6.294876273276469
        y: 2.3564053436919483
        z: 0.0
wait:
  approach1:
    position:
      x: 7.354957011662686
      y: 23.54583447482398
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.9936295230126899
      w: 0.1126959227193882
  approach2:
    position:
      x: 6.417241971006523
      y: 23.293313284595392
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.9938574810686658
      w: 0.11066755316643868
  cuboid:
    - - 5.530478314692662
      - 22.707294950778433
    - - 5.314449572896507
      - 23.68361553552213
    - - 4.340152013654879
      - 23.46730109152614
    - - 4.5561807554510345
      - 22.490980506782442
  last_updated: '2024-06-09 17:14:52.166498'
  location:
    orientation:
      w: 0.09274159057330929
      x: 0.0
      y: 0.0
      z: -0.9956902115507276
    position:
      x: 7.792123040557456
      y: 23.654717441934658
      z: 0.0
objects: { "cup": "coffee", "banana": "banana" }

yolo_person_model: "yolov8x-seg.pt"
yolo_objects_model: "yolov8x-seg.pt"
yolo_counter_model: "yolov8x-seg.pt"
