dishwasher:
  pose: 
    position: 
      x: 5.6505556976598355
      y: 4.267634141933843
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.8651222638416656
      w: 0.5015610317852371
  place_pose:
    position:
      x: 5.360
      y: 3.395
      z: 1.234
    orientation:
      x: -0.049
      y: -0.020
      z: -0.808
      w: 0.587
  pre_place_pose:
    position: 
      x: 4.746089584373821
      y: 4.507563515731061
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.731249201532089
      w: 0.6821104054760361


sink:
  pose:
    position: 
      x: 5.5462462041481695
      y: 4.1711570631533945
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.7897247117961702
      w: 0.6134613920846657
  pre_place_pose:
    position: 
      x: 5.599348425252851
      y: 4.375301058680274
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.7908038670948451
      w: 0.6120696396553571
  place_pose:
    position:
      x: 4.654
      y: 3.512
      z: 1.234
    orientation:
      x: -0.050
      y: -0.018
      z: -0.832
      w: 0.553

shelf:
  pose: 
    position: 
      x: 4.6262711795897165
      y: 5.042507859058248
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.9965311349028964
      w: 0.08322077366346367
  place_pose:
    position:
      x: 3.873
      y: 5.121
      z: 1.234
    orientation:
      x: 0.050
      y: -0.017
      z: 0.996
      w: 0.077
  pre_place_pose:
    pose: 
      position: 
        x: 4.943528139302953
        y: 4.992253934613047
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.9942236746102964
        w: 0.10732793133383065
table:
  pose: 
    position: 
      x: 6.244076988067995
      y: 5.455146058259334
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.6433794420694964
      w: 0.7655474469439132
  place_pose:
    position:
      x: 6.458
      y: 6.344
      z: 1.079
    orientation:
      x: -0.023
      y: 0.016
      z: 0.668
      w: 0.744

  pre_place_pose: 
    position: 
      x: 6.249905735992845
      y: 5.737744450700459
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.623249517266957
      w: 0.7820230426442082

fridge:
  pose:
    position: 
      x: 4.9609515214225945
      y: 5.938508565296619
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.989495703222031
      w: 0.1445622817512866
  place_pose:
    position:
      x: 4.269
      y: 6.330
      z: 1.567
    orientation:
      x: 0.023
      y: 0.098
      z: 0.982
      w: 0.162
kitchen:
  pose:
    position:
      x: 6.131939679982212
      y: 4.46258860864363
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.8864142489895283
      w: 0.4628928376939209