priors:
  names:
    - Sophie
    - Julia
    - Emma
    - Sara
    - Laura
    - Hayley
    - Susan
    - Fleur
    - GabriÃ«lle
    - Gabrielle
    - Robin
    - John
    - Liam
    - Lucas
    - William
    - Kevin
    - Jesse
    - Noah
    - Harrie
    - Peter

  drinks:
    - cola
    - ice tea
    - milk
    - water
    - big coke
    - fanta
    - dubbelfris

# WAIT POSE KITCHEN:
wait_pose:
  position:
    x: 1.9867316187022508
    y: 0.7879099771350105
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: -0.8156974576748943
    w: 0.5784787442445175

# WAIT AREA KITCHEN:
wait_area: [[2.67, 0.0], [2.5, -1.86], [0.79, -1.60], [1.0, -0.0]]

seat_pose:
  position:
    x: 2.2513155977453994
    y: 4.607534990369736
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.463219811993643
    w: 0.8862434235448938

search_motions: ["look_left", "look_right"]
sofa_point:
  x: 3.6489758491516113
  y: 7.049365997314453
  z: 0.5
seat_area: [[1.57, 6.1], [1.73, 7.9], [5.58, 7.49], [5.16, 4.79]]
sofa_area: [[2.65, 6.87], [2.79, 7.79], [4.61, 7.58], [4.50, 6.69]]

sweep: true
